sudo: false
language: node_js
node_js:
- 0.12
- 0.11
- 0.10
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_success:
  - npm run semantic-release
notifications:
# publish status to gitter chat room: https://gitter.im/reedia/generator-avionic
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/449e9c5af147ca23c74e
    on_success: always
    on_failure: always
    on_start: false  
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
