sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
- v5
- v4
- iojs-v2
- iojs-v1
- '0.12'
- '0.10'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - npm install -g gulp
  - npm install -g codeclimate-test-reporter
after_script:
- npm run-script coverage
- npm run-script coveralls  
after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < ./coverage/mocha/lcov.info
  - npm run semantic-release
