language: node_js
sudo: false
node_js:
- 0.12
- 4
- 5

cache:
  directories:
  - node_modules

before_script:
- npm install -g gulp

addons:
    code_climate:
        repo_token: 6cd58f101cfcf6016c0270065d65d01ca254524664f59e95e7a84e7c7db26789

after_script:
  - codeclimate-test-reporter < lcov.info
